[versions]

# Android SDK
androidCompileSdk = "37"
androidMinSdk = "24"
androidNdk = "28.2.13676358"

# Build script
androidGradlePlugin = "9.2.1"
googleProtobufGradlePlugin = "0.10.0"
java = "21"
kotlin = "2.3.21"
kotlinxCoroutines = "1.11.0"
ksp = "2.3.9"

# Androidx
androidxAnnotation = "1.10.0"
androidxActivity = "1.13.0"
androidxAppCompat = "1.7.1"
androidxCardView = "1.0.0"
androidxConstraintLayout = "2.2.1"
androidxCoreKtx = "1.19.0"
androidxDatastore = "1.2.1"
androidxFragmentKtx = "1.8.9"
androidxLifecycle = "2.10.0"
androidxLifecycleExtension = "2.2.0"
androidxNavigation = "2.9.8"
androidxRecyclerView = "1.4.0"
androidxViewPager2 = "1.1.0"
androidxRoom = "2.8.4"
androidxSplashScreen = "1.2.0"
androidxVectorDrawable = "1.2.0"
androidxComposeBom = "2026.08.00"

# Other
airbnbLottie = "6.7.1"
googleMaterial = "1.14.0"
kotlinSerializationJson = "1.11.0"
openCv = "4.12.0"
ncnn = "20260113"
googleDaggerHilt = "2.59.2"
googleProtobufRuntime = "4.35.1"

# Tests only
androidxArchCoreTesting = "2.2.0"
androidxTestCore = "1.7.0"
androidxTestExtJunit = "1.3.0"
junit = "4.13.2"
mockitoCore = "5.23.0"
mockitoKotlin = "6.3.0"
mockk = "1.14.11"
robolectric = "4.16.1"
espressoCore = "3.7.0"


[libraries]
acra-core = { module = "ch.acra:acra-core", version = "5.13.1" }

# Plugin dependencies for build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidxRoom" }
google-protobuf-gradlePlugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "googleProtobufGradlePlugin" }

# Dependencies used in build-logic. Might seem unused but check in files if that is the case
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestCore" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestCore" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# Androidx
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-cardView = { group = "androidx.cardview", name = "cardview", version.ref = "androidxCardView" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCoreKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragmentKtx" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerView" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "androidxViewPager2" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidxLifecycle" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "androidxLifecycleExtension" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-vectorDrawable = { group = "androidx.vectordrawable", name = "vectordrawable-animated", version.ref = "androidxVectorDrawable" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }

# Other
airbnb-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "airbnbLottie" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "googleDaggerHilt" }
google-dagger-hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "googleDaggerHilt" }
google-protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "googleProtobufRuntime" }
google-protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "googleProtobufRuntime" }


google-dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "googleDaggerHilt" }

# Tests only
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCoreTesting" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidxRoom" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }


[plugins]

# Plugins from external providers
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidxNavigationSafeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }
androidxRoom = { id = "androidx.room", version.ref = "androidxRoom" }
googleDaggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "googleDaggerHilt" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleProtobufGradle = { id = "com.google.protobuf", version.ref = "googleProtobufGradlePlugin" }
jetbrainsKotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrainsKotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Plugins defined by this project
buzbuz-androidApplication = { id = "com.buzbuz.gradle.android.application", version = "unspecified" }
buzbuz-androidLibrary = { id = "com.buzbuz.gradle.android.library", version = "unspecified" }
buzbuz-androidRoom = { id = "com.buzbuz.gradle.android.room", version = "unspecified" }
buzbuz-androidUnitTest = { id = "com.buzbuz.gradle.android.unittest", version = "unspecified" }
buzbuz-androidLocalTest = { id = "com.buzbuz.gradle.android.localtest", version = "unspecified" }
buzbuz-androidSigning = { id = "com.buzbuz.gradle.android.signing", version = "unspecified" }
buzbuz-flavour = { id = "com.buzbuz.gradle.android.flavour", version = "unspecified" }
buzbuz-obfuscation = { id = "com.buzbuz.gradle.obfuscation", version = "unspecified" }
buzbuz-buildParameters = { id = "com.buzbuz.gradle.build.parameters", version = "unspecified" }
buzbuz-hilt = { id = "com.buzbuz.gradle.android.hilt", version = "unspecified" }
buzbuz-kotlinSerialization = { id = "com.buzbuz.gradle.android.kotlin.serialization", version = "unspecified" }
buzbuz-protobuf = { id = "com.buzbuz.gradle.protobuf", version = "unspecified" }
buzbuz-sourceDownload = { id = "com.buzbuz.gradle.build.sourcedl", version = "unspecified" }
